name: Vue.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # 当推送到main分支时触发
  pull_request:
    branches: [ "main" ]  # 当对main分支发起PR时触发
  workflow_dispatch:      # 允许手动触发workflow

env:
  DOCKER_IMAGE_NAME: haochun1991/test  # 使用仓库名作为镜像名

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Vue project
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ DOCKER_IMAGE_NAME }}:latest
            ${{ DOCKER_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ DOCKER_IMAGE_NAME }}:buildcache,mode=max
